import 'package:quest_arcade_app/screens/games/find_numbers/models/level_model.dart';

final List<LevelModel> findNumbersLevelsRepository = [
  LevelModel(
    number: 0,
    digitsCount: 10,
    isDone: false,
    isAvailable: true,
    levelImage: 'assets/images/find-numbers/levels/level-1.png',
    doneImage: 'assets/images/find-numbers/levels/done-1.png',
    disableImage: 'assets/images/find-numbers/levels/level-1.png',
  ),
  LevelModel(
    number: 1,
    digitsCount: 15,
    isDone: false,
    isAvailable: false,
    levelImage: 'assets/images/find-numbers/levels/level-2.png',
    doneImage: 'assets/images/find-numbers/levels/done-2.png',
    disableImage: 'assets/images/find-numbers/levels/disable-2.png',
  ),
  LevelModel(
    number: 2,
    digitsCount: 20,
    isDone: false,
    isAvailable: false,
    levelImage: 'assets/images/find-numbers/levels/level-3.png',
    doneImage: 'assets/images/find-numbers/levels/done-3.png',
    disableImage: 'assets/images/find-numbers/levels/disable-3.png',
  ),
  LevelModel(
    number: 3,
    digitsCount: 25,
    isDone: false,
    isAvailable: false,
    levelImage: 'assets/images/find-numbers/levels/level-4.png',
    doneImage: 'assets/images/find-numbers/levels/done-4.png',
    disableImage: 'assets/images/find-numbers/levels/disable-4.png',
  ),
  LevelModel(
    number: 4,
    digitsCount: 30,
    isDone: false,
    isAvailable: false,
    levelImage: 'assets/images/find-numbers/levels/level-5.png',
    doneImage: 'assets/images/find-numbers/levels/done-5.png',
    disableImage: 'assets/images/find-numbers/levels/disable-5.png',
  ),
  LevelModel(
    number: 5,
    digitsCount: 35,
    isDone: false,
    isAvailable: false,
    levelImage: 'assets/images/find-numbers/levels/level-6.png',
    doneImage: 'assets/images/find-numbers/levels/done-6.png',
    disableImage: 'assets/images/find-numbers/levels/disable-6.png',
  ),
  LevelModel(
    number: 6,
    digitsCount: 40,
    isDone: false,
    isAvailable: false,
    levelImage: 'assets/images/find-numbers/levels/level-7.png',
    doneImage: 'assets/images/find-numbers/levels/done-7.png',
    disableImage: 'assets/images/find-numbers/levels/disable-7.png',
  ),
  LevelModel(
    number: 7,
    digitsCount: 45,
    isDone: false,
    isAvailable: false,
    levelImage: 'assets/images/find-numbers/levels/level-8.png',
    doneImage: 'assets/images/find-numbers/levels/done-8.png',
    disableImage: 'assets/images/find-numbers/levels/disable-8.png',
  ),
];

